import axios from "axios";
import { useCallback, useEffect, useRef, useState } from "react";
import { downloadBlankPublicDaycarePickupAuthorization, downloadPublicDaycarePickupAuthorization, getPublicDaycarePickupAuthorization, submitPublicDaycarePickupAuthorization, uploadPublicDaycarePickupAuthorization } from "../../../services/daycarePickupAuthorizationService";
import type { DaycareAuthorizedCollector, DaycarePickupAuthorizationPayload, DaycarePickupSignerRole, PublicDaycarePickupAuthorization } from "../../../types/daycarePickupAuthorization";
import styles from "./PickupAuthorizationSection.module.scss";

type Props = { token: string; onSubmitted: () => void };
const emptyCollector = (): DaycareAuthorizedCollector => ({ fullName: "", relationship: "", phone: "", israeliId: "" });
const roleLabels: Record<string, string> = { mother: "אם", father: "אב", guardian: "אפוטרופוס/ית" };
const statusLabels = { pendingReview: "ממתין לבדיקת המעון", completed: "התקבל ואושר", requiresCorrection: "נדרש תיקון" };
const canvasToBlob = (canvas: HTMLCanvasElement) => new Promise<Blob>((resolve, reject) => canvas.toBlob((blob) => blob ? resolve(blob) : reject(new Error("empty signature")), "image/png"));
const messageFromError = (error: unknown) => axios.isAxiosError<{ message?: string }>(error) ? error.response?.data?.message || "לא הצלחנו לשלוח את מורשי האיסוף." : "לא הצלחנו לשלוח את מורשי האיסוף.";

const PickupAuthorizationSection = ({ token, onSubmitted }: Props) => {
    const [data, setData] = useState<PublicDaycarePickupAuthorization | null>(null);
    const [collectors, setCollectors] = useState<DaycareAuthorizedCollector[]>([]);
    const [signedBy, setSignedBy] = useState(""); const [signerRole, setSignerRole] = useState<DaycarePickupSignerRole>("mother"); const [confirmed, setConfirmed] = useState(false); const [hasSignature, setHasSignature] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
    const canvasRef = useRef<HTMLCanvasElement>(null); const drawingRef = useRef(false);
    const applyPayload = useCallback((payload?: DaycarePickupAuthorizationPayload) => { if (!payload) return; setCollectors(payload.collectors); setSignedBy(payload.signedBy); setSignerRole(payload.signerRole); }, []);
    const load = useCallback(async () => { const next = await getPublicDaycarePickupAuthorization(token); setData(next); if (next.available) applyPayload(next.declaration?.payload); }, [applyPayload, token]);
    useEffect(() => { let active = true; void getPublicDaycarePickupAuthorization(token).then((next) => { if (!active) return; setData(next); if (next.available) applyPayload(next.declaration?.payload); }).catch(() => { if (active) setData(null); }); return () => { active = false; }; }, [applyPayload, token]);
    if (!data?.available) return null;
    const declaration = data.declaration;
    const point = (event: React.PointerEvent<HTMLCanvasElement>) => { const rect = event.currentTarget.getBoundingClientRect(); return { x: (event.clientX - rect.left) * (event.currentTarget.width / rect.width), y: (event.clientY - rect.top) * (event.currentTarget.height / rect.height) }; };
    const start = (event: React.PointerEvent<HTMLCanvasElement>) => { const context = event.currentTarget.getContext("2d"); if (!context) return; event.currentTarget.setPointerCapture(event.pointerId); const current = point(event); context.beginPath(); context.moveTo(current.x, current.y); context.strokeStyle = "#143a63"; context.lineWidth = 3; context.lineCap = "round"; drawingRef.current = true; };
    const draw = (event: React.PointerEvent<HTMLCanvasElement>) => { if (!drawingRef.current) return; const context = event.currentTarget.getContext("2d"); if (!context) return; const current = point(event); context.lineTo(current.x, current.y); context.stroke(); setHasSignature(true); };
    const stop = () => { drawingRef.current = false; }; const clear = () => { const canvas = canvasRef.current; canvas?.getContext("2d")?.clearRect(0, 0, canvas.width, canvas.height); setHasSignature(false); };
    const updateCollector = (index: number, field: keyof DaycareAuthorizedCollector, value: string) => setCollectors((current) => current.map((collector, collectorIndex) => collectorIndex === index ? { ...collector, [field]: field === "israeliId" ? value.replace(/\D/g, "").slice(0, 9) : value } : collector));
    const validCollectors = collectors.every((collector) => collector.fullName.trim().length >= 2 && collector.relationship.trim().length >= 2 && collector.phone.trim().length >= 7 && collector.israeliId.length === 9);
    const valid = validCollectors && signedBy.trim().length >= 2 && confirmed && hasSignature;
    const submit = async () => { if (!canvasRef.current || !valid) return; setBusy(true); setError(""); setNotice(""); try { const signature = await canvasToBlob(canvasRef.current); await submitPublicDaycarePickupAuthorization(token, { collectors, informationConfirmed: true, signedBy: signedBy.trim(), signerRole }, signature); setNotice("מורשי האיסוף נשלחו וממתינים לבדיקת צוות המעון."); await load(); onSubmitted(); } catch (submitError) { setError(messageFromError(submitError)); } finally { setBusy(false); } };
    const saveBlob = (blob: Blob, filename: string) => { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); };
    const downloadBlank = async () => { setError(""); try { saveBlob(await downloadBlankPublicDaycarePickupAuthorization(token), "מורשי-איסוף-למילוי-ידני.pdf"); } catch (downloadError) { setError(messageFromError(downloadError)); } };
    const downloadSigned = async () => { setError(""); try { saveBlob(await downloadPublicDaycarePickupAuthorization(token), "מורשי-איסוף-חתום.pdf"); } catch (downloadError) { setError(messageFromError(downloadError)); } };
    const uploadManual = async (file?: File) => { if (!file) return; setBusy(true); setError(""); setNotice(""); try { await uploadPublicDaycarePickupAuthorization(token, file); setNotice("הטופס החתום הועלה וממתין לבדיקת צוות המעון."); await load(); onSubmitted(); } catch (uploadError) { setError(messageFromError(uploadError)); } finally { setBusy(false); } };

    return <section className={styles.card} id="pickup-authorization" aria-labelledby="pickup-title">
        <header className={styles.header}><div><span className={styles.eyebrow}>שלב האיסוף</span><h2 className={styles.title} id="pickup-title">מורשי איסוף</h2><p className={styles.intro}>ההורים מופיעים אוטומטית. ניתן להוסיף אנשים נוספים שמורשים לאסוף את הילד/ה.</p></div>{declaration ? <span className={styles.status}>{statusLabels[declaration.status]}</span> : null}</header>
        {declaration?.parentMessage ? <p className={styles.correction}>{declaration.parentMessage}</p> : null}
        {data.canSubmit ? <div className={styles.form}>
            <details className={styles.manualOption}><summary className={styles.manualSummary}>מעדיפים למלא ולחתום ידנית?</summary><div className={styles.manualContent}><p className={styles.helper}>הורידו את הטופס, מלאו וחתמו, ולאחר מכן העלו PDF או צילום ברור.</p><div className={styles.actions}><button className={styles.secondary} type="button" disabled={busy} onClick={() => void downloadBlank()}>הורדת טופס להדפסה</button><label className={styles.uploadLabel}>העלאת טופס חתום<input className={styles.fileInput} type="file" accept="application/pdf,.pdf,image/jpeg,.jpg,.jpeg,image/png,.png" disabled={busy} onChange={(event) => void uploadManual(event.target.files?.[0])} /></label></div><span className={styles.helper}>PDF, JPG או PNG עד 10MB</span></div></details>
            <div className={styles.section}><h3 className={styles.sectionTitle}>הורים ואפוטרופוסים</h3><div className={styles.guardianList}>{data.guardians.map((guardian) => <div className={styles.guardian} key={`${guardian.fullName}-${guardian.phone}`}><strong>{guardian.fullName}</strong><span>{guardian.roleDetails || roleLabels[guardian.role] || guardian.role} · {guardian.phone}</span></div>)}</div></div>
            <div className={styles.section}><div className={styles.sectionHeading}><div><h3 className={styles.sectionTitle}>מורשי איסוף נוספים</h3><p className={styles.helper}>אין חובה להוסיף אדם נוסף.</p></div><button className={styles.secondary} type="button" disabled={collectors.length >= 10} onClick={() => setCollectors((current) => [...current, emptyCollector()])}>הוספת מורשה</button></div>{collectors.length === 0 ? <p className={styles.empty}>לא נוספו מורשי איסוף נוספים.</p> : <div className={styles.collectorList}>{collectors.map((collector, index) => <div className={styles.collector} key={index}><div className={styles.collectorHeader}><strong>מורשה {index + 1}</strong><button className={styles.remove} type="button" onClick={() => setCollectors((current) => current.filter((_, collectorIndex) => collectorIndex !== index))}>הסרה</button></div><div className={styles.grid}><label className={styles.label}>שם מלא<input className={styles.input} value={collector.fullName} onChange={(event) => updateCollector(index, "fullName", event.target.value)} /></label><label className={styles.label}>קרבה לילד/ה<input className={styles.input} value={collector.relationship} placeholder="למשל: סבתא, דוד" onChange={(event) => updateCollector(index, "relationship", event.target.value)} /></label><label className={styles.label}>טלפון<input className={styles.input} type="tel" value={collector.phone} onChange={(event) => updateCollector(index, "phone", event.target.value)} /></label><label className={styles.label}>מספר תעודת זהות<input className={styles.input} inputMode="numeric" autoComplete="off" maxLength={9} value={collector.israeliId} onChange={(event) => updateCollector(index, "israeliId", event.target.value)} /></label></div></div>)}</div>}</div>
            <div className={styles.section}><h3 className={styles.sectionTitle}>הצהרה וחתימה</h3><label className={styles.consent}><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />אני מאשר/ת כי האנשים המפורטים בטופס מורשים לאסוף את הילד/ה, ומתחייב/ת לעדכן את המעון בכל שינוי.</label><div className={styles.grid}><label className={styles.label}>שם מלא של החותם/ת<input className={styles.input} value={signedBy} onChange={(event) => setSignedBy(event.target.value)} /></label><label className={styles.label}>תפקיד<select className={styles.select} value={signerRole} onChange={(event) => setSignerRole(event.target.value as DaycarePickupSignerRole)}><option value="mother">אם</option><option value="father">אב</option><option value="guardian">אפוטרופוס/ית</option></select></label></div><span className={styles.helper}>חתימה באמצעות העכבר או האצבע</span><canvas ref={canvasRef} className={styles.signatureCanvas} width="700" height="220" onPointerDown={start} onPointerMove={draw} onPointerUp={stop} onPointerCancel={stop} /><div className={styles.actions}><button className={styles.secondary} type="button" onClick={clear}>ניקוי חתימה</button><button className={styles.primary} type="button" disabled={busy || !valid} onClick={() => void submit()}>{busy ? "שולח..." : declaration ? "שליחת טופס מתוקן" : "חתימה ושליחת מורשי האיסוף"}</button></div></div>
        </div> : declaration ? <div className={styles.actions}><button className={styles.secondary} type="button" onClick={() => void downloadSigned()}>הורדת מורשי האיסוף החתומים</button></div> : null}
        <div aria-live="polite">{notice ? <p className={styles.success}>{notice}</p> : null}{error ? <p className={styles.error}>{error}</p> : null}</div>
    </section>;
};
export default PickupAuthorizationSection;
