import type { Request, Response } from "express";
import type { DaycareAuthorizedCollector, DaycarePickupSignerRole } from "../types/daycarePickupAuthorization";
import { downloadBlankPickupAuthorization, downloadPickupAuthorizationForAdmin, downloadPickupAuthorizationForParent, getAdminPickupAuthorization, getPublicPickupAuthorization, reviewPickupAuthorization, submitPickupAuthorization, submitUploadedPickupAuthorization } from "../services/daycarePickupAuthorizationService";
import { DaycareOnboardingServiceError } from "../services/daycareOnboardingService";
import { logger } from "../utils/logger";

const errorResponse = (res: Response, error: unknown) => { if (error instanceof DaycareOnboardingServiceError) return res.status(error.statusCode).json({ success: false, code: error.code, message: error.message }); logger.error("Daycare pickup authorization request failed", error); return res.status(500).json({ success: false, message: "לא הצלחנו לבצע את הפעולה." }); };
const text = (value: unknown, max: number) => typeof value === "string" && value.trim().length > 0 && value.trim().length <= max ? value.trim() : null;
const parseInput = (value: unknown) => {
    if (!value || typeof value !== "object") return null; const raw = value as Record<string, unknown>; if (!Array.isArray(raw.collectors) || raw.collectors.length > 10 || raw.informationConfirmed !== true || !["mother", "father", "guardian"].includes(String(raw.signerRole))) return null;
    const collectors: DaycareAuthorizedCollector[] = []; for (const item of raw.collectors) { if (!item || typeof item !== "object") return null; const collector = item as Record<string, unknown>; const fullName = text(collector.fullName, 160); const relationshipText = text(collector.relationship, 100) ?? ""; const relationshipType = collector.relationshipType === "father" || ["אבא", "אב"].includes(relationshipText) ? "father" : "other"; const relationship = relationshipType === "father" ? "אבא" : relationshipText; const phone = text(collector.phone, 30); const israeliId = text(collector.israeliId, 20); if (!fullName || !relationship || !phone || !israeliId) return null; collectors.push({ fullName, relationship, relationshipType, phone, israeliId }); }
    const signedBy = text(raw.signedBy, 160); if (!signedBy) return null; return { collectors, informationConfirmed: true as const, signedBy, signerRole: raw.signerRole as DaycarePickupSignerRole };
};
const sendPdf = (res: Response, file: { bytes: Buffer; mimeType: string; filename: string }) => { res.setHeader("Content-Type", file.mimeType); res.setHeader("Content-Disposition", `attachment; filename="${file.filename}"`); res.setHeader("Cache-Control", "private, no-store"); return res.send(file.bytes); };

export const getPublicDaycarePickupAuthorization = async (req: Request, res: Response) => { try { return res.json({ success: true, data: await getPublicPickupAuthorization(req.params.token) }); } catch (error) { return errorResponse(res, error); } };
export const submitPublicDaycarePickupAuthorization = async (req: Request, res: Response) => { if (!req.file) return res.status(400).json({ success: false, message: "נדרשת חתימה מצוירת." }); let raw: unknown; try { raw = JSON.parse(String(req.body.payload ?? "")); } catch { return res.status(400).json({ success: false, message: "פרטי מורשי האיסוף אינם תקינים." }); } const input = parseInput(raw); if (!input) return res.status(400).json({ success: false, message: "יש להשלים את כל שדות החובה." }); try { return res.json({ success: true, data: await submitPickupAuthorization(req.params.token, input, req.file) }); } catch (error) { return errorResponse(res, error); } };
export const downloadBlankPublicDaycarePickupAuthorization = async (req: Request, res: Response) => { try { return sendPdf(res, await downloadBlankPickupAuthorization(req.params.token)); } catch (error) { return errorResponse(res, error); } };
export const uploadPublicDaycarePickupAuthorization = async (req: Request, res: Response) => { if (!req.file) return res.status(400).json({ success: false, message: "יש לבחור PDF או צילום של הטופס החתום." }); try { return res.json({ success: true, data: await submitUploadedPickupAuthorization(req.params.token, req.file) }); } catch (error) { return errorResponse(res, error); } };
export const downloadPublicDaycarePickupAuthorization = async (req: Request, res: Response) => { try { return sendPdf(res, await downloadPickupAuthorizationForParent(req.params.token)); } catch (error) { return errorResponse(res, error); } };
export const getAdminDaycarePickupAuthorization = async (req: Request, res: Response) => { try { return res.json({ success: true, data: await getAdminPickupAuthorization(req.params.onboardingId) }); } catch (error) { return errorResponse(res, error); } };
export const reviewAdminDaycarePickupAuthorization = async (req: Request, res: Response) => { const status = req.body?.status; if (status !== "completed" && status !== "requiresCorrection") return res.status(400).json({ success: false, message: "סטטוס הבדיקה אינו תקין." }); const correctionDisposition = req.body?.correctionDisposition; if (correctionDisposition !== undefined && correctionDisposition !== "preserveVersion" && correctionDisposition !== "discardFileAfterReplacement") return res.status(400).json({ success: false, message: "אופן שמירת הגרסה הקודמת אינו תקין." }); try { return res.json({ success: true, data: await reviewPickupAuthorization(req.params.id, status, typeof req.body.parentMessage === "string" ? req.body.parentMessage : undefined, correctionDisposition) }); } catch (error) { return errorResponse(res, error); } };
export const downloadAdminDaycarePickupAuthorization = async (req: Request, res: Response) => { try { return sendPdf(res, await downloadPickupAuthorizationForAdmin(req.params.id)); } catch (error) { return errorResponse(res, error); } };
